log4j.rootLogger= ALL , stdout , file

log4j.logger.com.tasnetwork.calibration.conveyor.conveyor=DEBUG,ConveyorDebug,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.conveyor=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.calib=DEBUG,CalibTestBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.calib=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.comm=DEBUG,ComTestBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.comm=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.ft=DEBUG,FunctionalTestBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.ft=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.ir=DEBUG,IrTestBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.ir=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.hv=DEBUG,HvTestBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.hv=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.verific=DEBUG,VerificTestBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.verific=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.verific_waiting=DEBUG,WaitingBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.verific_waiting=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.sta_nld1=DEBUG,StaNldtBay1,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.sta_nld1=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.sta_nld2=DEBUG,StaNldtBay2,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.sta_nld2=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.unloading=DEBUG,UnloadingBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.unloading=false

log4j.logger.com.tasnetwork.calibration.conveyor.bay.rejection=DEBUG,RejectionBay,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.bay.rejection=false

log4j.logger.com.tasnetwork.calibration.conveyor.plc=DEBUG,Plc,stdout
log4j.additivity.com.tasnetwork.calibration.conveyor.plc=false

log4j.logger.org.hibernate = WARN

# Redirect logs to console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.file=org.apache.log4j.FileAppender
log4j.appender.file.File=./logs/${AppName}_${Version}__${current.date.time}_log.txt
log4j.appender.file.Append=false
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.ConveyorDebug=org.apache.log4j.FileAppender
#log4j.appender.file.File=${AppName}_${Version}__${current.date.time}_log.txt
log4j.appender.ConveyorDebug.File=./logs/${AppName}_${Version}__${current.date.time}_ConveyorDebug_log.txt
log4j.appender.ConveyorDebug.Append=false
log4j.appender.ConveyorDebug.layout=org.apache.log4j.PatternLayout
log4j.appender.ConveyorDebug.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.CalibTestBay=org.apache.log4j.FileAppender
log4j.appender.CalibTestBay.File=./logs/${AppName}_${Version}__${current.date.time}_Calib_log.txt
log4j.appender.CalibTestBay.Append=false
log4j.appender.CalibTestBay.layout=org.apache.log4j.PatternLayout
log4j.appender.CalibTestBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.ComTestBay=org.apache.log4j.FileAppender
log4j.appender.ComTestBay.File=./logs/${AppName}_${Version}__${current.date.time}_Com_log.txt
log4j.appender.ComTestBay.Append=false
log4j.appender.ComTestBay.layout=org.apache.log4j.PatternLayout
log4j.appender.ComTestBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.FunctionalTestBay=org.apache.log4j.FileAppender
log4j.appender.FunctionalTestBay.File=./logs/${AppName}_${Version}__${current.date.time}_Ft_log.txt
log4j.appender.FunctionalTestBay.Append=false
log4j.appender.FunctionalTestBay.layout=org.apache.log4j.PatternLayout
log4j.appender.FunctionalTestBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.IrTestBay=org.apache.log4j.FileAppender
log4j.appender.IrTestBay.File=./logs/${AppName}_${Version}__${current.date.time}_Ir_log.txt
log4j.appender.IrTestBay.Append=false
log4j.appender.IrTestBay.layout=org.apache.log4j.PatternLayout
log4j.appender.IrTestBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n


# Redirect logs to a file
log4j.appender.HvTestBay=org.apache.log4j.FileAppender
log4j.appender.HvTestBay.File=./logs/${AppName}_${Version}__${current.date.time}_Hv_log.txt
log4j.appender.HvTestBay.Append=false
log4j.appender.HvTestBay.layout=org.apache.log4j.PatternLayout
log4j.appender.HvTestBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.VerificTestBay=org.apache.log4j.FileAppender
log4j.appender.VerificTestBay.File=./logs/${AppName}_${Version}__${current.date.time}_Verific_log.txt
log4j.appender.VerificTestBay.Append=false
log4j.appender.VerificTestBay.layout=org.apache.log4j.PatternLayout
log4j.appender.VerificTestBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.WaitingBay=org.apache.log4j.FileAppender
log4j.appender.WaitingBay.File=./logs/${AppName}_${Version}__${current.date.time}_VerificWaiting_log.txt
log4j.appender.WaitingBay.Append=false
log4j.appender.WaitingBay.layout=org.apache.log4j.PatternLayout
log4j.appender.WaitingBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.StaNldtBay1=org.apache.log4j.FileAppender
log4j.appender.StaNldtBay1.File=./logs/${AppName}_${Version}__${current.date.time}_StaNld_1_log.txt
log4j.appender.StaNldtBay1.Append=false
log4j.appender.StaNldtBay1.layout=org.apache.log4j.PatternLayout
log4j.appender.StaNldtBay1.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n

# Redirect logs to a file
log4j.appender.StaNldtBay2=org.apache.log4j.FileAppender
log4j.appender.StaNldtBay2.File=./logs/${AppName}_${Version}__${current.date.time}_StaNld_2_log.txt
log4j.appender.StaNldtBay2.Append=false
log4j.appender.StaNldtBay2.layout=org.apache.log4j.PatternLayout
log4j.appender.StaNldtBay2.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n



# Redirect logs to a file
log4j.appender.UnloadingBay=org.apache.log4j.FileAppender
log4j.appender.UnloadingBay.File=./logs/${AppName}_${Version}__${current.date.time}_Unloading_log.txt
log4j.appender.UnloadingBay.Append=false
log4j.appender.UnloadingBay.layout=org.apache.log4j.PatternLayout
log4j.appender.UnloadingBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n




# Redirect logs to a file
log4j.appender.RejectionBay=org.apache.log4j.FileAppender
log4j.appender.RejectionBay.File=./logs/${AppName}_${Version}__${current.date.time}_Rejection_log.txt
log4j.appender.RejectionBay.Append=false
log4j.appender.RejectionBay.layout=org.apache.log4j.PatternLayout
log4j.appender.RejectionBay.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n


# Redirect logs to a file
log4j.appender.Plc=org.apache.log4j.FileAppender
log4j.appender.Plc.File=./logs/${AppName}_${Version}__${current.date.time}_PlcClient_log.txt
log4j.appender.Plc.Append=false
log4j.appender.Plc.layout=org.apache.log4j.PatternLayout
log4j.appender.Plc.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1}:%L - %m%n



#log4j.logger.org.hibernate=info
#log4j.logger.org.hibernate=debug

### log HQL query parser activity
#log4j.logger.org.hibernate.hql.ast.AST=debug

### log just the SQL
#log4j.logger.org.hibernate.SQL=debug

### log JDBC bind parameters ###
#log4j.logger.org.hibernate.type=info
#log4j.logger.org.hibernate.type=debug

### log schema export/update ###
#log4j.logger.org.hibernate.tool.hbm2ddl=debug

### log HQL parse trees
#log4j.logger.org.hibernate.hql=debug